apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: jenkins-slave-maven-centos7
  name: jenkins-slave-maven-centos7
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-slave-maven-centos7:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: "FROM docker.io/openshift/jenkins-slave-maven-centos7:v3.9\r\nUSER
      root\r\nRUN yum -y install skopeo apb && \\\r\n    yum clean all\r\nUSER 1001"
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-slave-maven-centos7:v3.9
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: OA359j3WnrvkpBfXjOAK
    type: GitHub
  - generic:
      secret: cezsUyQVCDledPU371jh
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
