apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: mlbparks-dev
    name: mlbparks-dev
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: mlbparks-dev
      deploymentconfig: mlbparks-dev
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        post:
          execNewPod:
            command:
            - curl
            - mlbparks-dev.%GUID%-parks-dev.svc.cluster.local:8080/ws/data/load/
            containerName: mlbparks-dev
          failurePolicy: Abort
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mlbparks-dev
          deploymentconfig: mlbparks-dev
      spec:
        containers:
        - env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                key: DB_NAME
                name: mlbparks-dev-configmap
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: DB_PASSWORD
                name: mlbparks-dev-configmap
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: DB_PORT
                name: mlbparks-dev-configmap
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                key: DB_USERNAME
                name: mlbparks-dev-configmap
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                key: APPNAME
                name: mlbparks-dev-configmap
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: mlbparks-dev-configmap
          image: docker-registry.default.svc:5000/%GUID%-parks-dev/mlbparks-dev:0.0-0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: mlbparks-dev
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: nationalparks-dev
    name: nationalparks-dev
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: nationalparks-dev
      deploymentconfig: nationalparks-dev
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        post:
          execNewPod:
            command:
            - curl
            - nationalparks-dev.%GUID%-parks-dev.svc.cluster.local:8080/ws/data/load/
            containerName: nationalparks-dev
          failurePolicy: Abort
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nationalparks-dev
          deploymentconfig: nationalparks-dev
      spec:
        containers:
        - env:
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: DB_PASSWORD
                name: nationalparks-dev-configmap
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: DB_PORT
                name: nationalparks-dev-configmap
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                key: DB_USERNAME
                name: nationalparks-dev-configmap
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                key: APPNAME
                name: nationalparks-dev-configmap
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: nationalparks-dev-configmap
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                key: DB_NAME
                name: nationalparks-dev-configmap
          image: docker-registry.default.svc:5000/%GUID%-parks-dev/nationalparks-dev:0.0-0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nationalparks-dev
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: parksmap-dev
    name: parksmap-dev
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: parksmap-dev
      deploymentconfig: parksmap-dev
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: parksmap-dev
          deploymentconfig: parksmap-dev
      spec:
        containers:
        - env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: DB_HOST
                name: parksmap-dev-configmap
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                key: DB_NAME
                name: parksmap-dev-configmap
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: DB_PASSWORD
                name: parksmap-dev-configmap
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: DB_PORT
                name: parksmap-dev-configmap
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                key: DB_USERNAME
                name: parksmap-dev-configmap
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                key: APPNAME
                name: parksmap-dev-configmap
          image: docker-registry.default.svc:5000/%GUID%-parks-dev/parksmap-dev:0.0-0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: parksmap-dev
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: mlbparks-dev
      type: parksmap-backend
    name: mlbparks-dev
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mlbparks-dev
      deploymentconfig: mlbparks-dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: nationalparks-dev
      type: parksmap-backend
    name: nationalparks-dev
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nationalparks-dev
      deploymentconfig: nationalparks-dev
    sessionAffinity: None
    type: ClusterIP
  status:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: mlbparks-dev
    name: mlbparks-dev
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mlbparks-dev:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.7
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: vTS5SIZ5OeSK7e_6CAbv
      type: GitHub
    - generic:
        secret: cdR2teA5VCEEu7hZOMG6
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: nationalparks-dev
    name: nationalparks-dev
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nationalparks-dev:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: rmWW9gXJx37XcrHERw_K
      type: GitHub
    - generic:
        secret: t_9chSRhUqCQ704rJM24
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: parksmap-dev
    name: parksmap-dev
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: parksmap-dev:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: kJjOTMkchwy8TLBMkGhv
      type: GitHub
    - generic:
        secret: f46kHB8sajngQIeQDzXX
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
      openshift.io/image.dockerRepositoryCheck: 2018-10-26T05:38:08Z
    creationTimestamp: null
    generation: 3
    labels:
      build: mlbparks-dev
    name: mlbparks-dev
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
      openshift.io/image.dockerRepositoryCheck: 2018-10-26T05:38:09Z
    creationTimestamp: null
    generation: 3
    labels:
      build: nationalparks-dev
    name: nationalparks-dev
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
      openshift.io/image.dockerRepositoryCheck: 2018-10-26T05:37:04Z
    creationTimestamp: null
    generation: 3
    labels:
      build: parksmap-dev
    name: parksmap-dev
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  data:
    APPNAME: MLB Parks (Dev)
    DB_HOST: mongodb
    DB_NAME: parks
    DB_PASSWORD: mongodb
    DB_PORT: "27017"
    DB_USERNAME: mongodb
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: mlbparks-dev-configmap
- apiVersion: v1
  data:
    APPNAME: National Parks (Dev)
    DB_HOST: mongodb
    DB_NAME: parks
    DB_PASSWORD: mongodb
    DB_PORT: "27017"
    DB_USERNAME: mongodb
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: nationalparks-dev-configmap
- apiVersion: v1
  data:
    APPNAME: ParksMap (Dev)
    DB_HOST: mongodb
    DB_NAME: parks
    DB_PASSWORD: mongodb
    DB_PORT: "27017"
    DB_USERNAME: mongodb
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: parksmap-dev-configmap
kind: List
metadata: {}
