apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: mlbparks-pipeline
    name: mlbparks-pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: MLBParks
      git:
        ref: master
        uri: %REPO%
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GUID
          value: %GUID%
        - name: CLUSTER
          value: %CLUSTER%
        - name: REPO
          value: %REPO%
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: nationalparks-pipeline
    name: nationalparks-pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: Nationalparks
      git:
        ref: master
        uri: %REPO%
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GUID
          value: %GUID%
        - name: CLUSTER
          value: %CLUSTER%
        - name: REPO
          value: %REPO%
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: mlbparks-dev
      type: parksmap-backend
    name: mlbparks-dev
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mlbparks-dev
      deploymentconfig: mlbparks-dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: nationalparks-dev
      type: parksmap-backend
    name: nationalparks-dev
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: nationalparks-dev
      deploymentconfig: nationalparks-dev
    sessionAffinity: None
    type: ClusterIP
  status:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: parksmap-pipeline
    name: parksmap-pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ParksMap
      git:
        ref: master
        uri: %REPO%
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: GUID
          value: %GUID%
        - name: CLUSTER
          value: %CLUSTER%
        - name: REPO
          value: %REPO%
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
  status:
    lastVersion: 0
kind: List
metadata: {}
