apiVersion: v1
items:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus-registry
  spec:
    host: nexus-registry-%GUID%-nexus.apps.na39.openshift.opentlc.com
    port:
      targetPort: 5000
    tls:
      termination: edge
    to:
      kind: Service
      name: nexus-registry
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-10-23T05:40:51Z
        status: "True"
        type: Admitted
      host: nexus-registry-%GUID%-nexus.apps.na39.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: nexus3
    name: nexus3
  spec:
    host: nexus3-%GUID%-nexus.apps.na39.openshift.opentlc.com
    port:
      targetPort: 8081-tcp
    to:
      kind: Service
      name: nexus3
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-10-23T05:40:50Z
        status: "True"
        type: Admitted
      host: nexus3-%GUID%-nexus.apps.na39.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
kind: List
metadata: {}
